---
# Global variables for all hosts in the inventory
wordpress_version: "5.8"
docker_app_version: "latest"
vpn_user: "root"
vpn_password: "Meeshu@12345"
db_name: "wordpress_db"
db_user: "wp_user"
db_password: "wp_password"
docker_image_fastapi: "my_fastapi_app"
docker_image_react: "my_react_app"
wordpress_db_name: "gudliving_db"
wordpress_db_user: "gudliving_user"
wordpress_db_password: "Truth@12345"
wordpress_db_host: "localhost"
wordpress_version: "latest"
wordpress_admin_user: "admin"
wordpress_admin_password: "admin_password"
wordpress_admin_email: "admin@gudliving.com"
mysql_root_user: "gudliving_user"
mysql_root_password: "Truth@12345"