- name: Install Docker and Docker Compose
  apt:
    name:
      - docker.io
      - docker-compose
      - git
    state: latest
    update_cache: true

- name: Clone my_ledger_app repository
  git:
    repo: "https://github.com/pardeepgoel83/my_ledger_app.git"
    dest: /opt/my_ledger_app
    version: main

- name: Copy Docker Compose file
  template:
    src: docker-compose.yml.j2
    dest: /opt/my_ledger_app/docker-compose.yml

- name: Start ledger app containers
  community.docker.docker_compose:
    project_src: /opt/my_ledger_app
    state: present