---
- hosts: vpn_server
  become: true
  vars:
    ansible_python_interpreter: /usr/bin/python3
    wordpress_db_name: gudliving_db
    wordpress_db_user: gudliving_user
    wordpress_db_password: Truth@12345
    wordpress_db_host: localhost
    wordpress_version: latest
    wordpress_admin_user: admin
    wordpress_admin_password: admin_password
    wordpress_admin_email: admin@gudliving.com
  roles:
    - common
    # - vpn
    - wordpress
    - docker_app

- hosts: all
  become: true
  vars:
    wordpress_db_name: gudliving_db
    wordpress_db_user: gudliving_user
    wordpress_db_password: Truth@12345
    wordpress_db_host: localhost
    wordpress_version: latest
    wordpress_admin_user: admin
    wordpress_admin_password: admin_password
    wordpress_admin_email: admin@gudliving.com
  tasks:
    - name: Ensure all packages are up to date
      apt:
        update_cache: yes
        upgrade: dist

    - name: Include WordPress playbook
      include_tasks: wordpress.yml

    - name: Include Docker application playbook
      include_tasks: docker_app.yml

- hosts: webservers
  become: true
  roles:
    - wordpress
    - ledger