- name: Install required packages for WordPress
  apt:
    name:
      - apache2
      - mysql-server
      - php
      - libapache2-mod-php
      - php-mysql
      - git
    state: latest
    update_cache: true

- name: Start and enable Apache service
  service:
    name: apache2
    state: started
    enabled: true

- name: Start and enable MySQL service
  service:
    name: mysql
    state: started
    enabled: true

- name: Create WordPress database
  mysql_db:
    name: "{{ wordpress_db_name }}"
    state: present

- name: Create WordPress database user
  mysql_user:
    name: "{{ wordpress_db_user }}"
    password: "{{ wordpress_db_password }}"
    host: localhost
    priv: "{{ wordpress_db_name }}.*:ALL"
    state: present

- name: Clone gudliving_blog repository
  git:
    repo: "https://github.com/pardeepgoel83/gudliving_blog.git"
    dest: /var/www/html/gudliving_blog
    version: main

- name: Set ownership of WordPress files
  file:
    path: /var/www/html/gudliving_blog
    owner: www-data
    group: www-data
    state: directory
    recurse: yes

- name: Configure WordPress
  template:
    src: wp-config.php.j2
    dest: /var/www/html/gudliving_blog/wp-config.php

- name: Enable Apache rewrite module
  command: a2enmod rewrite
  notify: Restart Apache

- name: Restart Apache
  service:
    name: apache2
    state: restarted
  when: ansible_service_mgr == 'systemd'