- name: Install required packages for WordPress
  apt:
    name:
      - apache2
      - mysql-server
      - php
      - libapache2-mod-php
      - php-mysql
      - git
    state: latest
    update_cache: true

- name: Install PyMySQL for Ansible MySQL modules
  apt:
    name: python3-pymysql
    state: present
    update_cache: yes

- name: Start and enable Apache service
  service:
    name: apache2
    state: started
    enabled: true

- name: Start and enable MySQL service
  service:
    name: mysql
    state: started
    enabled: true

- name: Create WordPress database
  mysql_db:
    name: "{{ wordpress_db_name }}"
    login_user: "root"
    login_password: "Truth@12345"
    state: present

- name: Create WordPress database user
  mysql_user:
    name: "{{ wordpress_db_user }}"
    password: "{{ wordpress_db_password }}"
    host: localhost
    priv: "{{ wordpress_db_name }}.*:ALL"
    state: present

- name: Ensure www-data home directory exists
  file:
    path: /var/www
    state: directory
    owner: www-data
    group: www-data
    mode: '0755'
  become: true

- name: Remove existing gudliving_blog directory (if any)
  file:
    path: /var/www/html/gudliving_blog
    state: absent
  become: true

- name: Mark gudliving_blog directory as safe for Git (pre-clone)
  command: git config --global --add safe.directory /var/www/html/gudliving_blog
  become: true
  become_user: www-data
  environment:
    HOME: /var/www

- name: Clone gudliving_blog repository
  git:
    repo: "https://github.com/pardeepgoel83/gudliving_blog.git"
    dest: /var/www/html/gudliving_blog
    version: main
  become: true
  become_user: www-data
  environment:
    HOME: /var/www

- name: Mark gudliving_blog directory as safe for Git (post-clone)
  command: git config --global --add safe.directory /var/www/html/gudliving_blog
  become: true
  become_user: www-data
  environment:
    HOME: /var/www

- name: Set ownership of WordPress files
  file:
    path: /var/www/html/gudliving_blog/wordpress
    owner: www-data
    group: www-data
    state: directory
    recurse: yes
  become: true

- name: Configure WordPress
  template:
    src: wp-config.php.j2
    dest: /var/www/html/gudliving_blog/wordpress/wp-config.php

- name: Enable Apache rewrite module
  command: a2enmod rewrite
  notify: Restart Apache

- name: Restart Apache
  service:
    name: apache2
    state: restarted
  when: ansible_service_mgr == 'systemd'
